// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADGkk6A89OG_RZA6Zu6CW4sWedOx517NQ',
    appId: '1:938170352569:web:fb161e035892a9d46fec68',
    messagingSenderId: '938170352569',
    projectId: 'fmandi-a7e9b',
    authDomain: 'fmandi-a7e9b.firebaseapp.com',
    storageBucket: 'fmandi-a7e9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgumsZt7jD-KGAaE_ahV1mCK4y8BFaE-E',
    appId: '1:938170352569:android:b2c2756e828fdffc6fec68',
    messagingSenderId: '938170352569',
    projectId: 'fmandi-a7e9b',
    storageBucket: 'fmandi-a7e9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwinDI6XoYMY042ItSM-7u8z4f7hVoxc',
    appId: '1:938170352569:ios:b217c193419a0f136fec68',
    messagingSenderId: '938170352569',
    projectId: 'fmandi-a7e9b',
    storageBucket: 'fmandi-a7e9b.appspot.com',
    androidClientId: '938170352569-4g9doclh7u8nvc209374m9sk2u09b5es.apps.googleusercontent.com',
    iosClientId: '938170352569-8m77t2vgofp0lq84hmilq08nfcc1bujt.apps.googleusercontent.com',
    iosBundleId: 'com.example.emandi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwinDI6XoYMY042ItSM-7u8z4f7hVoxc',
    appId: '1:938170352569:ios:b217c193419a0f136fec68',
    messagingSenderId: '938170352569',
    projectId: 'fmandi-a7e9b',
    storageBucket: 'fmandi-a7e9b.appspot.com',
    androidClientId: '938170352569-4g9doclh7u8nvc209374m9sk2u09b5es.apps.googleusercontent.com',
    iosClientId: '938170352569-8m77t2vgofp0lq84hmilq08nfcc1bujt.apps.googleusercontent.com',
    iosBundleId: 'com.example.emandi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0aAMQc2yVuO6IRTdZHf1OcmsnimK-vLg',
    appId: '1:938170352569:web:7cd815a7319af2066fec68',
    messagingSenderId: '938170352569',
    projectId: 'fmandi-a7e9b',
    authDomain: 'fmandi-a7e9b.firebaseapp.com',
    storageBucket: 'fmandi-a7e9b.appspot.com',
  );

}